n_iters = 400_000
policy_hidden_sizes = [256, 256]
use_normalizer = true

[env]
id = "ModelBasedHalfCheetah-v2"
max_steps = 1000

[SAC]
n_exploration_steps = 10000
alpha = 0.2

[batch]
n_policy_grad_iters = 8
n_real = 64
n_starts = 64
horizon = 3
